### ISSUE TITLE
Is this compatible with the 7.4 community version?

### ISSUE THREAD

**Issue by douglascrp** [mwiede/camunda-cockpit-plugins#9]
I'm trying to use this plugin against a 7.4 community camunda server, but I'm not sure if I'm installing it the in the right way.

After packaging the project, I tried to place the resulting jar files inside both camunda/WEB-INF/lib folder and mycustomproject/WEB-INF/lib, but the heat map button is not shown in both cases.

So, please, let me know if, first, this plugin should work on 7.4, and second, the right way to deploy it.

Thank you in advance.

**Comment by mwiede** [comment]
Unfortunately, the plugin only works with camunda 7.2 community edition. The reason is, that after this release the diagram rendering inside of the camunda cockpit application totally changed.
But the camunda guys liked the idea and reimplemented the plugin as you can see in https://docs.camunda.org/manual/7.4/webapps/cockpit/bpmn/process-history-views/#heatmap. But this is only available in enterprise edition.

**Comment by douglascrp** [comment]
Thank you for the information.
